name: Rust

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build project
        run: cargo build --release

      - name: store exe on job
        uses: actions/upload-artifact@v2
        with:
          name: Er-Save-Editor.exe
          path: target/release/
          retention-days: 2
